highlighter: pygments
permalink: /:year/:month/:title.html

name: "What's Up Duck - Blog"
baseurl: "http://blog.whatsupduck.net"

paginate: 7
paginate_path: "archive/page:num"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
